### ISSUE TITLE
Unknown client when try to get policies

### ISSUE THREAD

**Issue by jvaca92** [Nerzal/gocloak#155]
**Describe the bug**
I try to get policies for my realm and client which I have created but always when I call GetPolicies by client I am getting *404 Not Found: Could not find client*. The wierd think is that another API endpoints I am able to call. 
Any hints where could be the problem becuase the client with realm should be OK.

**Expected behavior**
Get array of all policies.

**Additional context**
I am using gocloak v5 and the newest version of Keycloak which is 9.0.0.

**Comment by SVilgelm** [comment]
take a look at the the test for the `GetPolicies` function: https://github.com/Nerzal/gocloak/blob/master/client_test.go#L3031

As you can see it uses the `gocloakClientID` variable for Client's ID, what contain the ID of a client: https://github.com/Nerzal/gocloak/blob/master/client_test.go#L54

There are two different IDs: `Client.ID` and `Client.ClientID`.
* `Client.ClientID` is like a name, it contains a uniq name for a client
* `Client.ID` is a generated ID

in some API you need to use `Client.ClientID`, to work with other API you need to use `Client.ID`
The `GetPolicies` function requires to use `Client.ID`, not `Client.ClientID`, that's why you are getting 404 error

**Comment by jvaca92** [comment]
Sorry my mistake, I really used clientID instead of id of the client entity. Thanks for quick explaination.
