### ISSUE TITLE
Change the return type of GetUserGroups to Group

### ISSUE THREAD

**Issue by azerbe** [Nerzal/gocloak#245]
**Is your feature request related to a problem? Please describe.**

When you query for UserGroups (GET /{realm}/users/{id}/groups) you get a [Grouprepresentation](https://www.keycloak.org/docs-api/5.0/rest-api/index.html#_grouprepresentation) as result.
But currently the return type is a [UserGroup](https://github.com/Nerzal/gocloak/blob/c466757115d4eb939647e5259688074850f45f76/models.go#L256). This doesn't allow the use of querys like 

```
briefRep := false
groups, err := client.GetUserGroups(ctx, k.token.AccessToken, k.Realm, id, gocloak.GetGroupsParams{BriefRepresentation: &briefRep})
```

Something that is totally possible, if you query the API directly and if you are interested in informations like group attributes.

**Describe the solution you'd like**
Return [[]Group](https://github.com/Nerzal/gocloak/blob/c466757115d4eb939647e5259688074850f45f76/models.go#L286) instead.

**Comment by SVilgelm** [comment]
So, my question is Is it the bug we have from the very beginning or the return type is changed in some version?
Looks like that the USerGroup is a subset of Group, so I don't see any problems, it should be backward compatible with Keycloak's API, but form the Gocloak's point of view we must to release new major version, since it breaks backward compatibility
