### ISSUE TITLE
Token refresh and function signatures inconsistency

### ISSUE THREAD

**Issue by mweibel** [Nerzal/gocloak#276]
**Is your feature request related to a problem? Please describe.**
Using just gocloak without an automatic refresh of the token leads to an expired token after a short time. Using e.g. [gocloaksession](https://github.com/Clarilab/gocloaksession) helps with this issue and can add the token directly to the request when adding it using `resty.OnBeforeRequest()`. However when using this approach, using the library function are not that nice to use because you need to specify the token in every call (e.g. `CreateUser(ctx, token, realm, user)`)

**Describe the solution you'd like**
I'd prefer a built-in way of refreshing the token instead of using an external library for it, since it seems to be an essential part of a working keycloak client. 
This would lead to function signatures without token, since the token would be known in the gocloak instance. 

**Describe alternatives you've considered**
If that's not what the library would like to do, I could imagine one of the following approaches:
```golang
// CreateUser (Approach 1) which just proxies the calls to the actual client which is in a different instance and handles the token in a different way. This is to be able to retain the current API and avoid a breaking change.
func (client *gocloak) CreateUser(ctx, token, realm, user) (string, error) {
  client.something.Token(token)
  return client.something.CreateUser(ctx, realm, user)
}

// or another approach would be a fluent `.Token() *gocloak` function:
func (client *gocloak) Token(token string) *gocloak {
  client.token = token
}
func (client *gocloak) CreateUser(ctx, realm, user) (string, error) {
  // do request here and take token from `client.token`
}
```

I didn't test either of those approaches but just to give an idea how that could work.

**Comment by Nerzal** [comment]
The gocloaksession library is developed and maintained by my team. 

We decided to put that into a separate package, as it seemed out of scope to implement such behavior here, but i agree, that this could still be a valuable addition to gocloak itself.

**Comment by mweibel** [comment]
I guess it depends how you use it. If the token changes on most requests you do with it, it doesn't make sense. However if you own and manage the token, making a lot of requests with the same one, it makes a lot of sense.

**Comment by Nerzal** [comment]
To be honest, i currently see no way how we could have both ways. 

For my personal use in my team the suggested approach would work for nearly all use cases. 
But as this library tries to match as many needs as possible, i wouldn't change the current API.

**Comment by dj5k** [comment]
Hey!

Sorry for necroing this old issue. I found it while looking for this kind of solution to our problem: Re-using admin sessions for a Kubernetes controller.
Our current implementation is naive, such that every reconcile loop (e.g. client create, group delete, role mapping update etc.) creates a new session. Since that is both inefficient and creates lots of noise in the audit trail we want to re-use a single session.

We will likely use gocloaksession after some modifications as it currently is not compatible with admin login but provides a simple solution to what we want to achieve.

IMHO: Specifically for the admin user (managing the keycloak server) but also for general use cases I would like to see a token refresh solution as part of this library.
