### ISSUE TITLE
How to do Authorization Code flow with gocloak

### ISSUE THREAD

**Issue by dheeraj-326** [Nerzal/gocloak#362]
I could not find out a function in the library which I could use to help my UI client do a login with authorization code flow. Here I would like to use my GO service as the “Relying party” and Keycloak as my OpenID provider (keycloak-oidc). What I would like to do is for my UI to be able to hit the login endpoint in my GO service when the user initiates login then redirect to keycloak’s login (and LDAP logins in future) and then redirect back to UI after login is complete (typical authorization code flow). How can I achieve this using gocloak library or any other library available (please suggest)?

**Comment by jcarbelbide** [comment]
Hey, I'm still learning how to use Gocloak and keycloak, so if I get this wrong, please someone correct me! I was basically wondering the same thing a couple of weeks ago and the below is what I found. Hopefully it helps someone, since it's been a week and you've probably figured it out for yourself by now. 

My understanding is that gocloak is more of tool to interact with keycloak's admin API. If your client code is written in Javascript, there is luckily a really nice library that keycloak maintains to initiate the login process from the client side. Check out [this article](https://blog.logrocket.com/implement-keycloak-authentication-react/) that goes over how to do that in React. 

I'm not too much of a frontend guy, but from the above article, it looks like logging in is as simple as creating the keycloak object, and then calling `keycloak.login()` to initiate the login flow. That will redirect your frontend to the Keycloak login page, where your user can log in with their credentials or SSO. After successful login, the client should be redirected back to the original page (or wherever you specify), and you should have access to a bearer token generated by keycloak saying that you're authenticated for a set duration with your keycloak server. I think you can access the bearer token through the keycloak object as well. Something like `keycloak.token` (according to [this artcle](https://www.keycloak.org/docs/latest/securing_apps/index.html#properties)).

Now that your frontend has that token, you can make calls to your backend with that token. Stick it in the authorization header, and your backend should check that token for validity using some jwt library in a middleware or something. You will need to use the public key for your keycloak realm, which you can either grab for every authentication request, or just cache. To get the public key, you can use the gocloak function `GetCerts`, and parse the keys list you get back for the signing method your keycloak server is using. You can cache this since it shouldn't really change. You should be able to validate tokens without making any network calls to the keycloak server, if you wanted. 

Another way to validate tokens is to send the token to the keycloak introspection endpoint, and let keycloak check the token. It just may take a little longer because it's a network call, depending on where your backend server and keycloak server are hosted. You can use the gocloak function `RetrospectToken` to send the token to keycloak for introspection. 

For authorization, you can have a separate middleware. You can put role information in the bearer token in the keycloak admin dashboard using client scopes. The authz middleware can check the bearer token to make sure the token has the role for the requested resource. 

So I think that is the easiest way to handle logging in, and you get SSO pretty much for free. You also don't need to deal with sending your user information to your backend. The backend only cares about a valid token. You can also take advantage of all of the nice things built in to keycloak like forgot password flow, etc. 

However, if you still wanted to initiate logging in through your backend (which I think is more work), I think you would have to:
1. Create a realm.
2. Create a client. The client is your backend, since your backend is requesting to log in to keycloak with the credentials sent by the frontend. 
3. Note the clientID and clientSecret in the keycloak admin dashboard. You will need this for your backend. 
4. Your backend can use the gocloak command `Login` and send the clientID and clientSecret along with username and password to log in to keycloak. You will get a JWT bearer token back. 
5. Your frontend should keep that bearer token in local storage or something that's secure, and send it to your backend with every request that requires authen/authz. Your backend should validate the request using middleware or something. 

And I think you would have to implement forgot password, SSO, etc yourself.

**Comment by dheeraj-326** [comment]
> Hey, I'm still learning how to use Gocloak and keycloak, so if I get this wrong, please someone correct me! I was basically wondering the same thing a couple of weeks ago and the below is what I found. Hopefully it helps someone, since it's been a week and you've probably figured it out for yourself by now.
> 
> My understanding is that gocloak is more of tool to interact with keycloak's admin API. If your client code is written in Javascript, there is luckily a really nice library that keycloak maintains to initiate the login process from the client side. Check out [this article](https://blog.logrocket.com/implement-keycloak-authentication-react/) that goes over how to do that in React.
> 
> I'm not too much of a frontend guy, but from the above article, it looks like logging in is as simple as creating the keycloak object, and then calling `keycloak.login()` to initiate the login flow. That will redirect your frontend to the Keycloak login page, where your user can log in with their credentials or SSO. After successful login, the client should be redirected back to the original page (or wherever you specify), and you should have access to a bearer token generated by keycloak saying that you're authenticated for a set duration with your keycloak server. I think you can access the bearer token through the keycloak object as well. Something like `keycloak.token` (according to [this artcle](https://www.keycloak.org/docs/latest/securing_apps/index.html#properties)).
> 
> Now that your frontend has that token, you can make calls to your backend with that token. Stick it in the authorization header, and your backend should check that token for validity using some jwt library in a middleware or something. You will need to use the public key for your keycloak realm, which you can either grab for every authentication request, or just cache. To get the public key, you can use the gocloak function `GetCerts`, and parse the keys list you get back for the signing method your keycloak server is using. You can cache this since it shouldn't really change. You should be able to validate tokens without making any network calls to the keycloak server, if you wanted.
> 
> Another way to validate tokens is to send the token to the keycloak introspection endpoint, and let keycloak check the token. It just may take a little longer because it's a network call, depending on where your backend server and keycloak server are hosted. You can use the gocloak function `RetrospectToken` to send the token to keycloak for introspection.
> 
> For authorization, you can have a separate middleware. You can put role information in the bearer token in the keycloak admin dashboard using client scopes. The authz middleware can check the bearer token to make sure the token has the role for the requested resource.
> 
> So I think that is the easiest way to handle logging in, and you get SSO pretty much for free. You also don't need to deal with sending your user information to your backend. The backend only cares about a valid token. You can also take advantage of all of the nice things built in to keycloak like forgot password flow, etc.
> 
> However, if you still wanted to initiate logging in through your backend (which I think is more work), I think you would have to:
> 
> 1. Create a realm.
> 2. Create a client. The client is your backend, since your backend is requesting to log in to keycloak with the credentials sent by the frontend.
> 3. Note the clientID and clientSecret in the keycloak admin dashboard. You will need this for your backend.
> 4. Your backend can use the gocloak command `Login` and send the clientID and clientSecret along with username and password to log in to keycloak. You will get a JWT bearer token back.
> 5. Your frontend should keep that bearer token in local storage or something that's secure, and send it to your backend with every request that requires authen/authz. Your backend should validate the request using middleware or something.
> 
> And I think you would have to implement forgot password, SSO, etc yourself.

Thank you so much for this. Yes, I have figured out by now that gocloak comes in handy when I want to use the admin APIs. 
And answering to the part where you mentioned that we have to get user credentials ourselves if we have to use the backend: 
No, we don't. What I implemented is something as follows. 

1. UI calls {backend_api}/auth/login
2. Backend API redirects UI client to {keycloak}/realms/myrealm/protocol/openid-connect/auth/ with redirect URL as {backend_api}/auth/callback
3. Authentication happens and the handler at {backend_api}/auth/callback gets the authorization_code.
4. Above handler makes request to {{keycloak_url}}/realms/{{realm}}/protocol/openid-connect/token to get the access_token
5. Set-cookie and returns to UI client.

Here I have control at the backend and also not getting user credentials in the backend_api. We intend to implement single sign on using LDAP providers in the near future and hence this design.

**Comment by jcarbelbide** [comment]
Thats awesome, thank you so much! This helps me a lot to get a better understanding of how login flows can be implemented. I'll consider this approach for our auth as well.

**Comment by adrian-moisa** [comment]
@dheeraj-326 @jcarbelbide Is there any chance you guys can share some code. I'm struggling to piece together how to use gocloak for the authorisation flow. I've studied a lot about the theory behind OAuth2 and OIDC but now I'm trying to get some code running. I've searched a lot and I'm super stuck. I can't find some quality samples for gocloak. Also I'm trying to figure out why should I use gocloak in stead of go-oidc. So far the docs don't help a lot. Thank you for any advice!
